Repository tasoc/starclass, pull requests merged in 2021-01, with the labels that each got.

#52 Update dependencies
  .travis.yml
  requirements.txt
  starclass/XGBClassifier/xgbClassifier.py
Labels: cleanup, dependencies

#62 Create "fake" todo-files
  run_create_todolist.py
  run_starclass.py
  run_starclass_mpi.py
  starclass/BaseClassifier.py
  starclass/io.py
  starclass/todolist.py
  starclass/training_sets/tda_simulations.py
  starclass/training_sets/training_set.py
  tests/conftest.py
  tests/input/create_todolist/kplr001864183-2012179063303_llc.fits.gz
  tests/input/create_todolist/tess00029281992-s01-c1800-dr01-v04-tasoc-cbv_lc.fits.gz
  tests/test_todolist.py
  tests/test_trainingsets.py
Labels: enhancement

#59 Include feature names
  starclass/BaseClassifier.py
  starclass/MetaClassifier/Meta.py
  starclass/RFGCClassifier/RF_GC.py
  starclass/RFGCClassifier/RF_GC_featcalc.py
  starclass/SLOSH/SLOSH.py
  starclass/SortingHatClassifier/Sorting_Hat.py
  starclass/SortingHatClassifier/Sorting_Hat_featcalc.py
  starclass/XGBClassifier/xgbClassifier.py
  tests/test_classifiers.py
Labels: enhancement

#65 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#67 Random seed fix
  starclass/RFGCClassifier/RF_GC.py
  starclass/RFGCClassifier/RF_GC_featcalc.py
  starclass/RFGCClassifier/selfsom.py
Labels: bug
